const brandItems = [
    'Google',
    'Dell',
    'Amazon',
    'Apple',
    'Sharp',
    'Philips',
    'Nintendo',
    'Roku',
    'LG',
    'Sony',
    'Insignia™',
    'HP',
    'AT&T GoPhone',
    'Lenovo',
    'Harman/kardon',
    'SanDisk',
    'GoPro',
    'Epson',
    'Beats by Dr. Dre',
    'Boost Mobile',
    'Samsung',
    'Skullcandy',
    'Bose®',
    'JayBird',
    'DigiLand',
    'Acer',
    'ARRIS',
    'Sanus',
    'NETGEAR',
    'Kicker',
    'Rocketfish™',
    'Microsoft',
    'Cricket Wireless',
    'Pokemon',
    'Hammermill',
    'Minecraft',
    'Toshiba',
    'Energizer',
    'Motorola',
    'JVC',
    'JBL',
    'SONOS',
    'Canon',
    'VIZIO',
    'Westinghouse',
    'Yamaha',
    'Nikon',
    'BLU',
    'Arlo',
    'Belkin',
    'Nest',
    'Actiontec',
    'Linksys',
    'Asus',
    'AOC',
    'Verizon Prepaid',
    'Duracell',
    'Brother',
    'D-Link',
    'Rocketfish',
    'Rayovac',
    'Starbucks',
    'Simple Mobile',
    'Thermaltake',
    'Panasonic',
    'Fujifilm',
    'Roblox',
    'Ring',
    'XFINITY',
    'Hisense',
    'eBay',
    'Verizon Wireless Prepaid',
    'Polk Audio',
    'Philips Norelco',
    'Targus',
    'NVIDIA',
    'Kenwood',
    'Polaroid',
    'MSI',
    'Whalen Furniture',
    'Corsair',
    'Keurig',
    'iRobot',
    'J!NX',
    'Shark',
    'Onkyo',
    'Spotify',
    'Jabra',
    'Pioneer',
    'Jam',
    'Square',
    'Plantronics',
    'AT&T',
    'VTech',
    'JAM',
    'Oculus',
    'Fitbit',
    'iBUYPOWER',
    'Altec Lansing',
    'Klipsch',
    'Dyson',
    'eero',
    'MagicJack',
    'Jitterbug',
    'BISSELL',
    'Geek Squad',
    'PNY',
    'Virgin Mobile',
    'Frigidaire',
    'Memorex',
    'Ninja',
    'Gaming Heads',
    'iHome',
    'Oster',
    'Amana',
    'Whirlpool',
    'Honeywell',
    'Denon',
    'EVGA',
    'Alienware',
    'Chefman',
    'Dynex™',
    'j5 create',
    'CyberPowerPC',
    'Texas Roadhouse',
    'Bosch',
    'Darden Restaurants',
    'TracFone',
    'Texas Instruments',
    'Anova',
    'LIFX',
    'Nespresso',
    'ReTrak',
    'Piggyback',
];

export { brandItems };
